"""Render a Report as a self-contained, printable HTML document.

Clinicians want something to save to the chart or share. This produces one HTML
file with inline styling (no external assets), clickable source links, and a
print-friendly layout — open it and "Print → Save as PDF". The full evidence
trail travels with the document.
"""

from __future__ import annotations

import html

from .report import Report

_CSS = """
* { box-sizing: border-box; }
body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
       color: #1a1a1a; max-width: 820px; margin: 24px auto; padding: 0 20px; line-height: 1.5; }
h1 { font-size: 1.5rem; margin: 0 0 2px; }
h2 { font-size: 1.05rem; margin: 22px 0 6px; border-bottom: 2px solid #e5e7eb; padding-bottom: 3px; }
h3 { font-size: .9rem; margin: 12px 0 4px; color: #374151; }
.sub { color: #6b7280; font-size: .9rem; }
.summary { background: #f8fafc; border-left: 4px solid #2563eb; padding: 10px 14px; margin: 12px 0; }
.disclaimer { background: #fef2f2; border-left: 4px solid #dc2626; padding: 8px 12px;
              font-size: .82rem; color: #7f1d1d; margin: 10px 0; }
ul { margin: 4px 0 10px; padding-left: 20px; }
li { margin: 3px 0; }
.cite { color: #6b7280; font-size: .8rem; }
a { color: #2563eb; text-decoration: none; }
.badge { display: inline-block; background: #eef2ff; color: #3730a3; border-radius: 10px;
         padding: 1px 8px; font-size: .78rem; margin-left: 6px; }
.warn { color: #b45309; }
.audit { margin-top: 18px; color: #6b7280; font-size: .85rem; border-top: 1px solid #e5e7eb; padding-top: 8px; }
@media print { a { color: #1a1a1a; } body { margin: 0; } }
"""


def _esc(s) -> str:
    return html.escape(str(s), quote=True)


def _claims_ul(claims) -> str:
    rows = []
    for c in claims:
        mark = "" if c.is_supported else '<span class="warn">⚠ </span>'
        cites = []
        for ev in c.evidence:
            label = _esc(f"{ev.source}:{ev.record_id}")
            cites.append(f'<a href="{_esc(ev.url)}">{label}</a>' if ev.url else label)
        cite = f' <span class="cite">↳ {" · ".join(cites)}</span>' if cites else ""
        rows.append(f"<li>{mark}{_esc(c.statement)}{cite}</li>")
    return "<ul>" + "".join(rows) + "</ul>" if rows else "<p class='sub'>none</p>"


def report_html(report: Report) -> str:
    v = report.variant
    parts = [f"<h1>NeoVUS — {_esc(v.gene)} {_esc(v.hgvs or v.genomic)}</h1>"]
    parts.append(f'<div class="sub">{_esc(v.genomic)}'
                 + (f" · HPO: {_esc(', '.join(v.hpo_terms))}" if v.hpo_terms else "") + "</div>")

    for w in report.warnings:
        parts.append(f'<div class="disclaimer">⚠ {_esc(w)}</div>')

    if report.summary:
        parts.append(f'<div class="summary">{_esc(report.summary)}</div>')
    parts.append('<div class="disclaimer">Decision support on open public data — not a diagnosis '
                 'and not a medical device. Verify every claim against its linked source before clinical use.</div>')

    parts.append("<h2>Variant annotation</h2>" + _claims_ul(report.variant_evidence))

    parts.append("<h2>Candidate diseases</h2>")
    if report.candidate_diseases:
        rows = []
        for i, d in enumerate(report.candidate_diseases, 1):
            badge = f'<span class="badge">match {d.score:.0%}</span>' if d.score else ""
            rows.append(f"<h3>{i}. {_esc(d.name)} ({_esc(d.source_id)}){badge}</h3>" + _claims_ul(d.claims))
        parts.append("".join(rows))
    else:
        parts.append("<p class='sub'>none found</p>")

    if report.checklist:
        parts.append("<h2>Neonatal checklist</h2>")
        labels = {"symptom": "Symptoms / signs (HPO)", "workup": "Work-up", "follow-up": "Follow-up"}
        for cat in ("symptom", "workup", "follow-up"):
            items = [i for i in report.checklist if i.category == cat]
            if items:
                parts.append(f"<h3>{labels[cat]}</h3>")
                for it in items:
                    parts.append(_claims_ul(it.claims))

    if report.structural:
        parts.append("<h2>Protein-structural context</h2>")
        parts.append(f"<p>{_esc(report.structural.summary)}</p>" + _claims_ul(report.structural.claims))

    n_cite, n_bad = len(report.all_evidence()), len(report.unsupported_claims())
    parts.append(f'<div class="audit">Audit: {n_cite} citations · '
                 + (f'<span class="warn">{n_bad} unsupported</span>' if n_bad else "0 unsupported claims")
                 + " · generated by NeoVUS (open public data)</div>")

    return (f"<!doctype html><html><head><meta charset='utf-8'>"
            f"<title>NeoVUS {_esc(v.gene)} {_esc(v.hgvs or '')}</title>"
            f"<style>{_CSS}</style></head><body>{''.join(parts)}</body></html>")
